/**
 * The location-aware CRS index: which projected systems are valid where.
 *
 * The dataset is generated by scripts/build-epsg.ts and served as a static file,
 * like everything else here — there is no backend, and epsg.io is not CORS-open,
 * so a runtime lookup service was never available. It carries each definition's
 * proj4 string alongside its area of use, which is what lets one file answer
 * both "what can I use here?" and "how do I project into it?" without a second
 * round trip. Everything it contains is a metre-based projected CRS that has
 * been proved to transform in proj4 — see the generator for what that excludes
 * and why.
 */
import type { CrsDef } from '@/lib/geo/crs';
import { inFrance } from '@/lib/geo/france';

/** One CRS. Short keys: the file holds four thousand of these. */
export type CrsRecord = {
  /** EPSG code. */
  c: number;
  /** Published name, e.g. "RGF93 v1 / Lambert-93". */
  n: string;
  /** Area of use as EPSG describes it, e.g. "France - onshore and offshore…". */
  a: string;
  /** Area of use as **north, west, south, east** — EPSG's order, not GeoJSON's. */
  b: [number, number, number, number];
  /** proj4 definition string. */
  p: string;
  /** Accuracy of this CRS's datum tie to WGS84, in metres. Absent where EPSG
   *  states none, which is not the same as poor — see COARSE_TIE. */
  k?: number;
};

/**
 * A datum tie worse than this is not something to land on by default.
 *
 * It separates a datum's successive realizations by how well proj4 can actually
 * reach them: Tokyo datum is 9 m and JGD2011 is 1 m over the same wards, Fiji
 * 1956 is 7 m and Fiji 1986 is 2 m over the same island. Both legacy systems
 * publish the *smaller* area of use, so locality alone would rank them first and
 * quietly place a site a bus ride from where it belongs.
 *
 * A tier, not a filter — they stay in the list, below the ones we can hit.
 */
const COARSE_TIE = 5;

/** Unstated accuracy reads as fine, not as bad: plenty of current national CRSs
 *  simply carry no figure. */
const tier = (r: CrsRecord): number => (r.k !== undefined && r.k > COARSE_TIE ? 1 : 0);

/**
 * Does this record's area of use reach past the country it names?
 *
 * An area of use is published as a bounding box, and a box around a country is
 * not the country. France's is the one that hurts: EPSG:2154 is registered with
 * a southern edge at 41.15°N and the nine RGF93 / CCxx conic zones as wide
 * latitude bands, so all of them contain Barcelona, Bilbao and Zaragoza. Ranking
 * on box area then hands a Spanish site Lambert-93, which is the complaint this
 * rule exists to answer — with it, northern Spain lands on ETRS89 / UTM 29-31N
 * like the rest of the country.
 *
 * Only France is described this way, because France is the only country the app
 * carries a shape for; the same box problem at other borders (Brussels and
 * Aachen reaching Amersfoort / RD New, Dublin reaching British National Grid) is
 * untouched. Matching on the area string is safe here: of the 31 France records
 * in the index, all 31 are metropolitan — the overseas départements are
 * published under their own names, so Guadeloupe and Réunion cannot be caught.
 *
 * A tier, not a filter, exactly as COARSE_TIE is. A French system is still a
 * legitimate thing to ask for from over the border, and stays in the picker —
 * it just is not what a site there lands on by itself.
 */
const namesFrance = (r: CrsRecord): boolean => /^France\b/.test(r.a);

const spill = (r: CrsRecord, home: boolean): number => (!home && namesFrance(r) ? 1 : 0);

let pending: Promise<CrsRecord[]> | null = null;

/**
 * The index, fetched once and kept.
 *
 * A failed fetch clears the cache rather than poisoning it, so opening the field
 * again retries instead of reporting a stale failure forever — the file is 1.2 MB
 * and the most likely reason to miss it is a flaky connection, not a missing
 * deployment.
 */
export function loadEpsgIndex(): Promise<CrsRecord[]> {
  pending ??= fetch('/epsg.json')
    .then((r) => {
      if (!r.ok) throw new Error(String(r.status));
      return r.json() as Promise<CrsRecord[]>;
    })
    .catch((e: unknown) => {
      pending = null;
      throw e;
    });
  return pending;
}

/**
 * Is the point inside this CRS's area of use?
 *
 * The longitude test has two branches on purpose. An area that crosses the
 * antimeridian is published with its west edge greater than its east one — UTM
 * zone 60, Fiji and Chukotka all are — and a plain min/max comparison would
 * reject every point in exactly the places those CRSs exist to serve.
 */
export const containsPoint = (r: CrsRecord, lat: number, lon: number): boolean => {
  const [n, w, s, e] = r.b;
  if (lat > n || lat < s) return false;
  return w <= e ? lon >= w && lon <= e : lon >= w || lon <= e;
};

/**
 * Rough size of the area of use, in square degrees weighted by latitude.
 *
 * Only ever compared against another one of these, so the unit does not matter —
 * the cosine is there so that a Svalbard grid does not read as larger than a
 * French one covering the same ground.
 */
export const areaOf = (r: CrsRecord): number => {
  const [n, w, s, e] = r.b;
  const span = w <= e ? e - w : e - w + 360;
  return span * (n - s) * Math.cos((((n + s) / 2) * Math.PI) / 180);
};

/**
 * Every CRS valid at the point, most local first.
 *
 * Ranking by the size of the area of use is what puts a national grid above a
 * UTM zone above a continental system, without anyone maintaining a table of
 * which country prefers what: a CRS published for one département is a better
 * answer for a site inside it than one published for a hemisphere.
 *
 * Ties are common and not arbitrary — they are the successive realizations of
 * one datum over the same ground (Amersfoort RD Old and RD New; NAD83 alongside
 * its HARN, NSRS2007 and 2011 readjustments), all published with an identical
 * area of use. The higher code is the later registration, so it wins.
 */
export const candidatesAt = (list: CrsRecord[], lat: number, lon: number): CrsRecord[] => {
  // Once for the whole list, not once per record: the index holds four thousand
  // of them and the polygon test is a ray cast over sixty-odd vertices.
  const home = inFrance(lat, lon);
  return list
    .filter((r) => containsPoint(r, lat, lon))
    .sort(
      (x, y) =>
        spill(x, home) - spill(y, home) ||
        tier(x) - tier(y) ||
        areaOf(x) - areaOf(y) ||
        y.c - x.c,
    );
};

/**
 * What to select for a site nobody has chosen a CRS for.
 *
 * A curated code wins when one covers the site. Those four exist because they
 * are the national grid a deliverable in that country is expected in, and no
 * amount of ranking recovers that from the registry: EPSG publishes London
 * Survey Grid, the HS2 and MML07 railway grids over London too, all of them
 * more local than EPSG:27700 and none of them what anyone means.
 *
 * Everywhere else the smallest containing area of use is the best available
 * guess, and the picker is one click away when it guesses wrong.
 *
 * Two things decide which curated code, when more than one covers the site.
 *
 * Inside France, one that names France wins. EPSG:25832 is a UTM zone shared by
 * eight countries and is registered with a smaller box than Lambert-93 — whose
 * own box is half Atlantic — so ranking by area alone handed Nice, Cannes,
 * Strasbourg, Metz, Besançon and both Corsican cities a German-flavoured UTM
 * zone instead of the grid every French deliverable is drawn on. Box area cannot
 * see that; the polygon can.
 *
 * Outside it, the search skips the spilled records rather than scanning the
 * whole list, or a curated code would be found however far it had been demoted —
 * which is precisely how EPSG:2154 kept winning in Spain.
 */
export const bestAt = (
  list: CrsRecord[],
  curated: readonly string[],
  lat: number,
  lon: number,
): CrsRecord | undefined => {
  const home = inFrance(lat, lon);
  const here = candidatesAt(list, lat, lon);
  const pick = (want: (r: CrsRecord) => boolean): CrsRecord | undefined =>
    here.find((r) => curated.includes(String(r.c)) && want(r));
  return (home ? pick(namesFrance) : undefined) ?? pick((r) => !spill(r, home)) ?? here[0];
};

/**
 * The record as the build pipeline wants it.
 *
 * EPSG names a projected CRS "<base CRS> / <projection>", so the part before the
 * separator is the geodetic datum the IFC header asks for. Names without one are
 * rare and are their own best answer.
 */
export const toCrsDef = (r: CrsRecord): CrsDef => ({
  def: r.p,
  name: r.n,
  datum: r.n.includes(' / ') ? r.n.slice(0, r.n.indexOf(' / ')) : r.n,
});

export const findRecord = (list: CrsRecord[], code: string): CrsRecord | undefined =>
  list.find((r) => r.c === Number(code));
